# Generated by Django 5.1 on 2024-08-30 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id_cuestionario', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('nivel', models.CharField(choices=[('1M', '1º Medio'), ('2M', '2º Medio'), ('3M', '3º Medio'), ('4M', '4º Medio')], max_length=2)),
                ('materia', models.CharField(choices=[('BIO', 'Biología'), ('FIS', 'Física'), ('QUI', 'Química')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('texto_pregunta', models.TextField()),
                ('nivel', models.CharField(choices=[('1M', '1º Medio'), ('2M', '2º Medio'), ('3M', '3º Medio'), ('4M', '4º Medio')], max_length=2)),
                ('materia', models.CharField(choices=[('BIO', 'Biología'), ('FIS', 'Física'), ('QUI', 'Química')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('tipo', models.CharField(blank=True, choices=[('admim', 'Admin'), ('invitado', 'Invitado'), ('estudiante', 'Estudiante'), ('tutor', 'Tutor')], default='NONE', max_length=100, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamenUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.FloatField()),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cuestionario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('texto_respuesta', models.TextField()),
                ('es_correcta', models.BooleanField()),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='api.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examen_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='api.examenusuario')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pregunta')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.respuesta')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaCuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='api.cuestionario')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuestionarios', to='api.pregunta')),
            ],
            options={
                'unique_together': {('cuestionario', 'pregunta')},
            },
        ),
    ]
