# Generated by Django 5.1 on 2024-08-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamenUsuario',
            new_name='Resultado',
        ),
        migrations.RemoveField(
            model_name='respuestausuario',
            name='examen_usuario',
        ),
        migrations.RemoveField(
            model_name='respuestausuario',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='respuestausuario',
            name='respuesta',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('invitado', 'Invitado'), ('estudiante', 'Estudiante'), ('tutor', 'Tutor')], default='estudiante', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='PreguntaCuestionario',
        ),
        migrations.DeleteModel(
            name='RespuestaUsuario',
        ),
    ]
