# Generated by Django 5.1 on 2024-08-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_examenusuario_resultado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionario',
            name='pregunta',
            field=models.ManyToManyField(blank=True, null=True, to='api.pregunta'),
        ),
    ]
