# Generated by Django 5.1 on 2024-08-30 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cuestionario_pregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cuestionario',
            field=models.ManyToManyField(blank=True, null=True, to='api.cuestionario'),
        ),
    ]
