# Generated by Django 5.1 on 2024-08-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usuario_cuestionario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuestionario',
            old_name='id_cuestionario',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='pregunta',
            old_name='id_pregunta',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='respuesta',
            old_name='id_respuesta',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='resultado',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
