# Generated by Django 5.1 on 2024-08-30 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_id_cuestionario_cuestionario_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cuestionario',
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
