# Generated by Django 5.1 on 2024-08-30 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_cuestionario_usuario_usuario_cuestionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuestionario',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cuestionario',
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='preguntas',
            field=models.ManyToManyField(blank=True, to='api.pregunta'),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='usuario',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='cuestionarios', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
