# Generated by Django 5.1 on 2024-08-30 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_cuestionario_pregunta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuestionarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
